
services:

  db:
    image: postgres:17.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
    networks:
      - custom
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  custom:
    driver: bridge
