
services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - custom
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  custom:
    driver: bridge
